project:
  type: website
  output-dir: docs

website:
  title: "U12F BVC Caluso"
  favicon: images/foxvolleyball3.png
  navbar:
    left:
      - href: allenamenti.qmd
        text: Allenamenti
      - href: partite.qmd
        text: Partite
      - href: ct.qmd
        text: Commenti tecnico-tattici
    right: 
      - icon: youtube
        href: https://studio.youtube.com/playlist/PLuLJwY97FamexM2F6711BmqySUYCotgZ0/videos
      - text: Calendari
        menu: 
          - text: "Prima fase"
            href: https://docs.google.com/spreadsheets/d/1FYoLm8xXQP6Q8xbBYOuhOg_Xc8TOdEPT/edit#gid=190893738
      - text: Classifica
        menu: 
          - text: "Prima fase"
            href: https://docs.google.com/spreadsheets/d/1FYoLm8xXQP6Q8xbBYOuhOg_Xc8TOdEPT/edit#gid=658309003
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



