```{r setup}
#| echo: false
#| message: false
#| warning: false
# Load libraries
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(lubridate))
library(fs)

# Load scripts
source(paste0(here::here(), "/scripts/999_functions.R"))
```

L'allenamento di oggi {{< meta date >}} si è svolto al {{< meta params.palestra >}}.

### Valutazione dell'allenamento  {{< fa gauge-simple-high size=normalsize >}}

```{r}
#| echo: false
#| message: false
#| warning: false
df <- tribble(
    ~variable, ~percentage,
    "Impegno collettivo", params$impegno,
    "Raggiungimento\ndell'obiettivo", params$obiettivo,
    "Soddisfazione\ndell'allenatore", params$allenatore,
    "Miglioramenti attesi", params$miglioramenti,
    "Voto", params$voto) |>  
    mutate(group = ifelse(percentage <0.5, "red",
                          ifelse(percentage>=0.5 & percentage<0.7, "orange","green")),
           label = paste0(percentage * 100, "%"),
           title = factor(variable))

ggplot(df, aes(fill = group, ymax = percentage, ymin = 0, xmax = 2, xmin = 1)) +
 geom_rect(aes(ymax=1, ymin=0, xmax=2, xmin=1), fill ="#ece8bd") +
 geom_rect() + 
 coord_polar(theta = "y",start=-pi/2) + xlim(c(0, 2)) + ylim(c(0,2)) +
 geom_text(aes(x = 0, y = 0, label = label, colour=group), size=6.5) +
 # geom_text(aes(x=1.5, y=1.5, label=title), size=4.2) + 
 facet_wrap(~title, ncol = 3) +
 theme_void() +
 scale_fill_manual(values = c("red"="#C9146C", "orange"="#DA9112", "green"="#129188")) +
 scale_colour_manual(values = c("red"="#C9146C", "orange"="#DA9112", "green"="#129188")) +
 theme(strip.background = element_blank(),
       strip.text.x = element_text(size = 13)) +
 guides(fill="none") +
 guides(colour="none")
```

### Presenze {{< fa child-reaching size=normalsize >}}

```{r presenze}
#| echo: false
#| message: false
#| warning: false
pres <- readr::read_csv(paste0(here::here(), "/data/presenze.csv"), show_col_types = FALSE)
players <- readr::read_csv(paste0(here::here(), "/data/elencoAtlete.csv"), show_col_types = FALSE)

if(!lubridate::dmy(params$date) %in% pres$date){
    pres2 <- players |>
      dplyr::bind_rows(players  |>
                         dplyr::mutate(date = lubridate::dmy(params$date),
                                       assenti = ifelse(cognome %in% params$assenti, 1, 0)))

    fs::file_copy(paste0(here::here(), "/data/presenze.csv"),
              paste0(here::here(), "/data/presenze_old.csv"),
              overwrite = TRUE)

    readr::write_csv(pres2, paste0(here::here(), "/data/presenze.csv"))

    # # If a mistake is made before commit
    # system("git restore data/presenze.csv")
    # system("git restore data/presenze_old.csv")
}

x <- readr::read_csv(paste0(here::here(), "/data/presenze.csv"), show_col_types = FALSE)

x |>
    dplyr::filter(date %in% lubridate::dmy(params$date))  |>
    dplyr::mutate(date = format(date, "%d-%m"),
           assenti = ifelse(assenti == 1, "X", ""))  |>
    dplyr::select(-date, -id, -nascita, -numero) |>
    gt::gt()  |>
    gtExtras::gt_theme_538()
```


## Classifica Bagnerone {{< fa ranking-star size=normalsize >}}

### Classifica mensile

```{r}
#| echo: false
#| message: false
#| warning: false
####################### da modificare
# class <- readr::read_tsv(paste0(here::here(), "/data/003_dati/classificaRaw.tsv"), show_col_types = FALSE)
# players <- readr::read_table(paste0(here::here(), "/data/003_dati/players.tsv"), show_col_types = FALSE)
# 
# if(!lubridate::ymd(quarto::quarto_inspect(fs::dir_ls(".", regex = "qmd$"))$formats$html$metadata$date) %in% class$date){
#     class <- classifica(players,
#             date = str_remove_all(quarto::quarto_inspect(fs::dir_ls(".", regex = "qmd$"))$formats$html$metadata$date,
#                           "-"),
#             vincitori = c(40,30,27,9,28))
# 
#     fs::file_copy(paste0(here::here(), "/data/003_dati/classificaRaw.tsv"),
#                   paste0(here::here(), "/data/003_dati/classificaRaw_old.tsv"),
#                   overwrite = TRUE)
#     write_tsv(class, paste0(here::here(), "/data/003_dati/classificaRaw.tsv"))
#     
#     # # If a mistake is made before commit
#     # system("git restore data/003_dati/classificaRaw.tsv")
#     # system("git restore data/003_dati/classificaRaw_old.tsv")
# }
# 
# 
# 
# x2 <- readr::read_tsv(paste0(here::here(), "/data/classificaRaw.tsv"), show_col_types = FALSE)
# 
# 
# x2 |> 
#     dplyr::left_join(x) |> 
#     dplyr::mutate(mese = lubridate::month(params$date)) |> 
#     dplyr::filter(mese == lubridate::month(params$date)) |> 
#     dplyr::mutate(Punteggio = dplyr::case_when(vincitore == 1 & assenti == 0 ~ 3,
#                                  vincitore == 0 & assenti == 0 ~ 1,
#                                  TRUE ~ 0)) |> 
#     dplyr::group_by(cognome, nome) |> 
#     dplyr::summarise(Classifica = sum(Punteggio)) |> 
#     dplyr::ungroup() |> 
#     dplyr::arrange(desc(Classifica), cognome) |> 
#     gt::gt() |> 
#     gtExtras::gt_theme_538()

```

### Classifica generale

```{r}
#| echo: false
#| message: false
#| warning: false

# x2 <- read_tsv(paste0(here::here(), "/data/003_dati/classificaRaw.tsv"))
# 
# 
# x2 %>%
#     select(-Numero) %>% 
#     left_join(x) %>% 
#     mutate(Punteggio = case_when(vincitori == 1 & assenti == 0 ~ 3,
#                                  vincitori == 0 & assenti == 0 ~ 1,
#                                  TRUE ~ 0)) %>% 
#     group_by(Cognome, Nome) %>% 
#     summarise(Classifica = sum(Punteggio)) %>% 
#     ungroup %>% 
#     arrange(desc(Classifica), Cognome) %>% 
#     gt::gt() %>% 
#     gtExtras::gt_theme_538()

```

## Video dell'allenamento {{< fa video size=normalsize >}}

```{r}
#| echo: false
#| message: false
#| warning: false

if (!is.na(params$url)){
  paste0("{{< video ", params$url," >}}")
} else {
  cat(paste0("Nessun video per questo allenamento."))
}

```

```{r}
#| echo: false
#| message: false
#| warning: false

tit <- paste0("Allenamento ", params$allenamento, " del ", params$date)
```

---
title: "`r tit`"
---